/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rentaautomoviles;

/**
 *
 * @author Usuario
 */
public class frmMenu extends javax.swing.JFrame {

    //agregar un objeto de la clase carros
    //nuevo atributo para el formulario menu
    Carros miscarros = new Carros();
    /**
     * Creates new form frmMenu
     */
    public frmMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuRentar = new javax.swing.JMenu();
        mnuDisponibles = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        mnuDevolver = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuSalir = new javax.swing.JMenu();
        menusalir = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mnuRentar.setText("Rentar Autos");
        mnuRentar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuRentarActionPerformed(evt);
            }
        });

        mnuDisponibles.setText("Ver autos disponibles");
        mnuDisponibles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDisponiblesActionPerformed(evt);
            }
        });
        mnuRentar.add(mnuDisponibles);

        jMenuBar1.add(mnuRentar);

        jMenu3.setText("Devolver Vehiculos");

        mnuDevolver.setText("Ver vehiculos por devolver");
        jMenu3.add(mnuDevolver);

        jMenuBar1.add(jMenu3);

        jMenu5.setText("Gestionar Vehiculos");

        jMenuItem1.setText("Agregar");
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Modificar");
        jMenu5.add(jMenuItem2);

        jMenuItem3.setText("Eliminar");
        jMenu5.add(jMenuItem3);
        jMenu5.add(jSeparator1);

        mnuSalir.setText("Ventana");

        menusalir.setText("Salir");
        menusalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusalirActionPerformed(evt);
            }
        });
        mnuSalir.add(menusalir);

        jMenu5.add(mnuSalir);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 949, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menusalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusalirActionPerformed
     
        System.exit(0);
    }//GEN-LAST:event_menusalirActionPerformed

    private void mnuRentarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuRentarActionPerformed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_mnuRentarActionPerformed

    private void mnuDisponiblesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDisponiblesActionPerformed
        // TODO add your handling code here:
         frmRentar rentar = new frmRentar(this,true, miscarros);
        rentar.setVisible(true);
    }//GEN-LAST:event_mnuDisponiblesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menusalir;
    private javax.swing.JMenuItem mnuDevolver;
    private javax.swing.JMenuItem mnuDisponibles;
    private javax.swing.JMenu mnuRentar;
    private javax.swing.JMenu mnuSalir;
    // End of variables declaration//GEN-END:variables
}

